Sterling Hughes's fixes

diff --git a/reconf b/reconf
--- a/reconf
+++ b/reconf
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: reconf,v 1.3 2000-08-30 11:54:57 bagder Exp $
+# $Id: reconf,v 1.4 2001-05-30 07:59:47 bagder Exp $
 #
 # re autoconf/automake shell script
 #
@@ -9,7 +9,7 @@ die(){
 	echo "$@" ; exit
 }
 
-aclocal -I .	|| die "ahhhhh"
-autoheader	|| die "ahhhhh"
-automake	|| die "ahhhhh"
-autoconf	|| die "ahhhhh"
+aclocal -I . || die "The command 'aclocal -I .' failed"
+autoheader   || die "The command 'autoheader' failed"
+automake     || die "The command 'automake' failed"
+autoconf     || die "The command 'autoconf' failed"
