- Bas Mevissen reported http://curl.haxx.se/bug/view.cgi?id=2479030 pointing   out that 'reconf' didn't properly point out the m4 subdirectory when running   aclocal.

diff --git a/reconf b/reconf
--- a/reconf
+++ b/reconf
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# $Id: reconf,v 1.4 2001-05-30 07:59:47 bagder Exp $
+# $Id: reconf,v 1.5 2008-12-31 20:35:46 bagder Exp $
 #
 # re autoconf/automake shell script
 #
@@ -9,7 +9,7 @@ die(){
 	echo "$@" ; exit
 }
 
-aclocal -I . || die "The command 'aclocal -I .' failed"
+aclocal -I . -I m4 || die "The command 'aclocal -I . -I m4' failed"
 autoheader   || die "The command 'autoheader' failed"
 automake     || die "The command 'automake' failed"
 autoconf     || die "The command 'autoconf' failed"
